idade = int(input("what are you age?"))
if idade < 6 : input(print("lindinhaa"))
if idade < 18: input(print("voce nao pode dirigir"))
if idade > 60: input(print("Melhor idade"))
else         : input(print("Liberado para dirigir"))